# Generated by Django 4.0.3 on 2022-04-02 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_proyectos_proyecto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objetivos_espesificos',
            new_name='Objetivos_especificos',
        ),
    ]
