# Generated by Django 4.0.3 on 2022-04-02 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_rename_objetivos_espesificos_objetivos_especificos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objetivos_especificos',
            old_name='Proyecto',
            new_name='proyecto',
        ),
    ]
