# Generated by Django 4.0.3 on 2022-04-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_rename_proyecto_objetivos_especificos_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='porcentaje_avance',
            field=models.IntegerField(null=True),
        ),
    ]
