# Generated by Django 4.0.3 on 2022-04-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_proyecto_porcentaje_avance'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivos_especificos',
            name='estado',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('F', 'Finalizado'), ('E', 'En ejecucion')], max_length=1),
        ),
    ]
