# Generated by Django 4.0.3 on 2022-04-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_objetivos_especificos_estado_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivos_especificos',
            name='estado',
            field=models.BooleanField(null=True, verbose_name='Efectuado'),
        ),
    ]
