# Generated by Django 4.0.3 on 2022-04-04 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_objetivos_especificos_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivos_especificos',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.proyecto'),
        ),
    ]
