# Generated by Django 4.0.3 on 2022-04-04 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_objetivos_especificos_proyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objetivos_especificos',
            old_name='proyecto',
            new_name='proyecto_id',
        ),
    ]
