# Generated by Django 4.0.3 on 2022-04-04 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_rename_proyecto_objetivos_especificos_proyecto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objetivos_especificos',
            old_name='proyecto_id',
            new_name='proyecto',
        ),
    ]
