# Generated by Django 4.0.3 on 2022-04-05 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0012_alter_objetivos_especificos_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
