# Generated by Django 4.0.3 on 2022-04-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_proyecto_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('FFinalizado', 'Finalizado'), ('En ejecucion', 'En ejecucion')], max_length=20),
        ),
    ]
